version: '3'

services:
  recipes_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  api:
    image: recipes-api
    entrypoint: ["/app/entrypoint.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - recipes_database
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  pgdata: